Improve KISSConfig
PRBonn/kiss-icp pull request #63
Opened 2023-02-10 16:41 UTC by markuspi

## Problem

When specifying a custom YAML config, all config values needed to be specified. There was no fallback behavior to selectively override values.

## Solution

This PR introduces `pydantic` to validate and manage the configration.
The default values are defined in `config.py`.
YAML config files can override as many or as few items as needed.
Cleaned up generated yaml file: Output file is plain YAML without `!!python/object/new:easydict.EasyDict`

## Changes

* Remove `easydict` dependency
* Add `pydantic` dependency
* Change dataclass-based config to pydantic based config
* Add custom loader for YAML
* Remove default yaml path from CLI. Default values are now retrieved directly from config.py.
* Rename `default.yaml` to `basic.yaml` to avoid confusion. Editing this file only has effect when it is referenced via `--config`!

2023-02-13 16:10 UTC, nachovizzo requested changes
I think I end up requesting a lot. Please tell me if you can't solve all the issues, I will merge your changes and modify it afterwards.

Thanks again for your contributions!!!

2023-02-13 16:10 UTC, nachovizzo commented on src/python/kiss_icp/pipeline.py
> +        config: KISSConfig,
This change is in general desire, but I see the disadvantage of always having to build a `KISSConfig` object to use the pipeline. The other arguments are more "standard" which basically means I can fire up a python shell now, and `from kiss_icp.pipeline import Odometrypipeline` and run it as it it.

Would you mind reverting this back to the old bheavior?

2023-02-13 16:10 UTC, nachovizzo commented on src/python/kiss_icp/tools/cmd.py
> -        f"{get_package_dir()}/config/default.yaml",
`get_package_dir` function can also be removed

2023-02-17 09:12 UTC, nachovizzo commented on setup.py
> +            "pydantic",
This is possible, but it's a pain. So, dropping this idea

2023-02-17 10:25 UTC, nachovizzo commented
Merging these changes in #69

2023-02-17 10:25 UTC, closed without merging

2023-02-17 10:42 UTC, markuspi commented
Thanks for refining 👍